name: Build OpenWRT for Archer C6 v4 US

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git libncurses5-dev zlib1g-dev gawk gettext unzip file libssl-dev python3 python3-distutils

    - name: Clone OpenWRT source
      run: |
        git clone https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy custom config and DTS
      run: |
        cp .config openwrt/
        cp qca9563_tplink_archer-c6-v4-us.dts openwrt/target/linux/ath79/dts/

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: openwrt/bin/targets/ath79/generic/*.bin
